const controller = require('./controllers');
const router = require('express').Router();
const upload = require('./middleware/multer.js');
const auth = require('./controllers/auth.js');

router.get('/session', auth.checkSession);
router.post('/signup', auth.signUp);
router.post('/login', auth.logIn);
router.get('/auth/google', auth.googleLogin);
router.get('/auth/google/callback', auth.googleLoginCallback);
router.get('/logout', auth.logOut);
router.get('/search/:searchTerm/:searchValue', auth.isLogin, controller.redirectSearch);
router.get('/home', controller.posts.getAll);
router.get('/comments', controller.comments.get);
router.post('/comments', auth.isLogin, controller.comments.post);
router.get('/restaurants', controller.restaurants);
router.get('/dishes', controller.dishes);
router.get('/likes', controller.postLikes.get);
router.get('/reviews', controller.reviews);
router.post('/likes', auth.isLogin, controller.postLikes.post);
router.get('/posts', auth.isLogin, controller.posts.getAll);
router.get('/user/:username', auth.isLogin, controller.posts.getByUsername);
router.get('/rating', auth.isLogin, controller.posts.getByRating);
router.get('/dish/:dishname', auth.isLogin, controller.posts.getByDish);
router.get('/restaurant/:name', auth.isLogin, controller.posts.getByRestaurant);
router.post('/submit', upload.single('image'), controller.submit);
router.post('/votes/upvote', auth.isLogin, controller.dishLikes.upVote);
router.post('/votes/downvote', auth.isLogin, controller.dishLikes.downVote);
router.get('/user/profile', auth.isLogin, controller.users.getProfile);

module.exports = router;
